---
abstract: 'Needlessly OO module to scrape card images off of the'
author:
  - 'Satoshi Yagi <satoshi.yagi@yahoo.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-MobileTradeFun
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 0
  AnyEvent::HTTP: 0
  Encode: 0
  LWP::Simple: 0
  Log::Log4perl: 0
  Mojo::DOM: 0
  URI::Encode: 0
  perl: 5.006
version: 0.09
